proyecto2023-main/blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

# Urls de app noticias
urlpatterns = [

    path('', views.inicio, name="inicio"),

    # url para el detalle de la noticia por pk
    path('detalle/<int:pk>/', views.Detalle_Noticias, name='detalle'),

    # url del formulario de contacto
    path('contacto', views.Contact.as_view(), name="contacto"),

    # URL COMENTARIO
    path('comentario', views.Comentar_Noticia, name='comentar'),
    
    # crear noti
    path('registrar_noticia/', views.CrearNoticia.as_view(), name='registrar_noticia'),

    # Registro de Usuarios
    path('registro/', views.Registro.as_view(), name="registro"),
    
    path('editar/<int:pk>/', views.editar_noticia, name='editar_noticia'),

    path('borrar/<int:pk>/', views.borrar_noticia, name='borrar_noticia'),
]

proyecto2023-main/blog/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [

    path('registro/', views.Registro.as_view(), name="registro"),

]

proyecto2023-main/blog/blog/urls.py
from django.contrib import admin
# importamos include para poder trabajar con las urls de noticias
from django.urls import path, include
# from apps.noticias import views
from . import views

# url del login
from django.contrib.auth import views as auth
from django.conf.urls.static import static

from django.conf import settings

# URL PRINCIPAL
urlpatterns = [
    # path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    # path para la url de la vista de home
    path('', views.home, name="home"),
    # path tiene 3 parametros direccion url, funcion de la vista(views),
    # path de nosotros
    path('nosotros/', views.nosotros, name="nosotros"),

    # ---------- URL APP NOTICIA-----------
    path('noticia/', include('apps.noticias.urls')),

    # LOGIN
    # path('usuarios/login', views.login, name='login')
    path('login/', auth.LoginView.as_view(template_name='noticias/login.html'), name='login'),
    # ultimo error de la clase solucionado
    # path('logout/', auth.LoginView.as_view(), name='logout'),
    # cambiar LoginView por LogoutView
    path('logout/', auth.LogoutView.as_view(), name='logout'),

    # Registro
    # path('usuarios/', include('apps.usuarios.urls')),
    
     #Mejores Juegos
    path("recomendaciones/", views.recomendaciones, name="recomendaciones")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semana13/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

proyecto2023-main/blog/apps/noticias/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usuario(AbstractUser):
    pass 

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nombre


class Noticia(models.Model):
    titulo = models.CharField(max_length=150)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.titulo


class Contacto(models.Model):
    nombre = models.CharField(max_length=60)
    correo = models.EmailField()
    asunto = models.CharField(max_length=40)
    texto = models.TextField()

    def __str__(self) -> str:
        return self.nombre
#


class Comentario(models.Model):
    texto = models.TextField(null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    

    def __str__(self) -> str:
        return f"{self.noticia} {self.texto}"

proyecto2023-main/blog/apps/usuarios/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):
    pass

proyecto2023-main/blog/apps/noticias/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Contacto, Noticia, Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='apellido', required=True)
    password1 = forms.CharField(
        label='contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='contraseña2', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

class LoginForm(AuthenticationForm):
    class Meta:
        fields = ['username', 'password']




class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = "__all__"

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ('titulo', 'cuerpo', 'imagen', 'categoria_noticia')
        

proyecto2023-main/blog/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario


class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='apellido', required=True)
    password1 = forms.CharField(
        label='contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='contraseña2', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

blog/views.py
from django.shortcuts import render

# Create your views here.

proyecto2023-main/blog/apps/noticias/views.py
# dependencias de Django
from django.shortcuts import render, HttpResponse, redirect
# Importacion de Modelos
from .models import Noticia, Categoria, Comentario, Contacto
#importacion de Formularios
from .forms import NoticiaForm, ContactoForm, RegistroForm
# importamos reverse lazy para los comentarios
from django.urls import reverse_lazy
# importacion del decorador para verificar logueo
from django.contrib.auth.decorators import login_required
# Clase mixta para verificar que un usuario este logueado antes de ejecutar
from django.contrib.auth.mixins import LoginRequiredMixin
# Importacion de la dependencia para crear vistas en la BD 
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.views import View
from .forms import LoginForm
from django.shortcuts import render, get_object_or_404, redirect

# Clases de Registro de Usuarios


class Registro(View):
    template_name = 'noticias/registro.html'

    def get(self, request):
        form = RegistroForm() 
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegistroForm(request.POST) 
        if form.is_valid():
            form.save()
            return redirect('login')
        return render(request, self.template_name, {'form': form})


class Login(View):
    template_name = 'noticias/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Lógica para el inicio de sesión exitoso (opcional)
                return redirect('inicio')
        return render(request, self.template_name, {'form': form})




@login_required
def inicio(request):
    contexto = {}
    id_categoria = request.GET.get('id', None)
    orden = request.GET.get('orden', 'nuevas')  # Obtenemos el parámetro 'orden' de la URL o establecemos el valor predeterminado 'nuevas'

    if id_categoria:
        noticias = Noticia.objects.filter(categoria_noticia=id_categoria)
    else:
        noticias = Noticia.objects.all()  # una lista

    if orden == 'nuevas':
        noticias = noticias.order_by('-fecha')  # Ordenamos por fecha más reciente (descendente)
    elif orden == 'viejas':
        noticias = noticias.order_by('fecha')  # Ordenamos por fecha más antigua (ascendente)
    elif orden == 'alf':
        noticias = noticias.order_by('titulo')  # Ordenamos alfabéticamente por título (ascendente)

    contexto['noticias'] = noticias

    cat = Categoria.objects.all().order_by('nombre')
    contexto['categorias'] = cat

    return render(request, 'noticias/inicio.html', contexto)


@login_required
def Detalle_Noticias(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk=pk)
    contexto['noticia'] = n

    c = Comentario.objects.filter(noticia=n)
    contexto['comentarios'] = c

    return render(request, 'noticias/detalle.html', contexto)

@login_required
def editar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = NoticiaForm(instance=noticia)

    return render(request, 'noticias/editar.html', {'form': form, 'noticia': noticia})

@login_required
def borrar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    
    if request.method == 'POST':
        noticia.delete()
        return redirect('noticias:inicio')  

    return render(request, 'noticias/borrar.html', {'noticia': noticia})



class CrearNoticia(LoginRequiredMixin, CreateView):
	model = Noticia
	form_class = NoticiaForm
	template_name = 'noticias/registrar_noticia.html'
	success_url = reverse_lazy('noticias:inicio')
	
	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.autor = self.request.user
		return super(CrearNoticia, self).form_valid(form)




class Contact(CreateView):
    model = Contacto
    form_class = ContactoForm
    template_name = 'contacto/formulario.html'
    success_url = reverse_lazy('noticias:registrar_noticia')
    
    def form_valid(self, form):
        contacto = form.save(commit=False)
        return super(Contact, self).form_valid(form)


@login_required
def Comentar_Noticia(request):
    comentario = request.POST.get('comentario', None)
    user = request.user
    noti = request.POST.get('id_noticia', None)
    noticia = Noticia.objects.get(pk=noti)
    coment = Comentario.objects.create(
        usuario=user, noticia=noticia, texto=comentario)
    return redirect(reverse_lazy('noticias:detalle', kwargs={"pk": noti}))

proyecto2023-main/blog/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.
# importts
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegistroForm


class Registro(CreateView):
    # forms django
    form_class = RegistroForm
    success_url = reverse_lazy('login')
    template_name = 'usuarios/registro.html'

proyecto2023-main/blog/blog/views.py
from django.shortcuts import render, redirect
from apps.noticias.models import Noticia

def home(request):
    # Obtener las últimas 4 noticias ordenadas por fecha de publicación descendente
    noticias = Noticia.objects.order_by('-fecha')[:4]

    # Pasar las noticias al contexto
    context = {'noticia_0': noticias[0],
               'noticia_1': noticias[1],
               'noticia_2': noticias[2],
               'noticia_3': noticias[3]}
    
    return render(request, 'home.html', context)


def nosotros(request):
    return render(request, 'nosotros.html', {
        "saludo": "Hola mundo",
        "nombre": "Soy el contexto",
        "autor": "Dani"
    })
    
def recomendaciones(request):
    return render(request, "juegos.html")

proyecto2023-main/blog/templates/noticias/borrar.html
{% extends 'base.html' %}
{% block contenido %}
  <h1>Borrar Noticia</h1>
  <p>¿Estás seguro de que quieres borrar la noticia "{{ noticia.titulo }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Borrar</button>
  </form>
{% endblock contenido %}

proyecto2023-main/blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%}Noticia{%endblock titulo%}

{% block contenido%}

<div style="background-color: rgb(214, 195, 110); margin: 1vw 1vw 1vw 30vw; width: 40vw; border-style: solid; border-radius: 25px; border-color: rgb(236, 132, 28);">
    <h1>{{noticia.titulo}}</h1>
    <img src="{{noticia.imagen.url}}" alt="" width="150">
    <p>{{noticia.cuerpo}}</p>
    <p>{{noticia.fecha}}</p>
    <p>{{noticia.categoria_noticia}}</p>
    
    <!-- Agregar botones de editar y borrar -->
    <a href="{% url 'noticias:editar_noticia' noticia.pk %}">Editar</a>
    <a href="{% url 'noticias:borrar_noticia' noticia.pk %}">Borrar</a>

</div>

<h3>Comentarios</h3>
{% for com in comentarios %}
    <p><strong>{{ com.usuario }}</strong> {{ com.fecha }}</p>
    <p> comentario: {{ com.texto }}</p>
{% endfor %}

<hr> <!-- hr = Horizontal rule (linea horizontal) -->

<form action="{% url 'noticias:comentar' %}" method="post">{% csrf_token %}
    <textarea name="comentario" cols="30" rows="3"></textarea>
    <input type="text" name="id_noticia" value="{{ noticia.pk }}" hidden="">
    <input type="submit" value="comentar">
</form>

{% endblock contenido%}

proyecto2023-main/blog/templates/noticias/detalle_hugo.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%}Noticia{%endblock titulo%}

{% block contenido%}

<div style="background-color: rgb(214, 195, 110); margin: 1vw 1vw 1vw 25vw; width: 50vw; border-style: solid; border-color: rgb(236, 132, 28);;">
    <h1>{{noticia}}</h1>
    <img src="{{noticia.imagen.url}}" alt="" width="150">
    <p>{{noticia.cuerpo}}</p>
    <p>{{noticia.fecha}} / {{noticia.categoria_noticia}}</p>
</div>

<!-- <input type="submit" value="Editar"> -->

<h3>Comentarios</h3>
{% for com in comentarios %}
<div style="background-color: rgb(214, 195, 110); margin: 1vw 1vw 1vw 30vw; width: 40vw; border-style: solid; border-radius: 25px; border-color: rgb(236, 132, 28);;">
    <p><strong>{{ com.usuario }}</strong> {{ com.fecha }}</p>
    <p><em> {{ com.texto }} </em></p>
</div>

{% endfor %}

<hr> <!-- hr = Horizontal rule (linea horizontal) -->

<form action="{% url 'noticias:comentar' %}" method="post">{% csrf_token %}
    <textarea name="comentario" cols="30" rows="3"></textarea>
    <input type="text" name="id_noticia" value="{{ noticia.pk }}" hidden="">
    <input type="submit" value="comentar">
</form>

{% endblock contenido%}

proyecto2023-main/blog/templates/noticias/editar.html
{% extends 'base.html' %}
{% block contenido %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title">{{ noticia.titulo }}</h5>
            <p class="card-text">{{ noticia.cuerpo }}</p>
            <img src="{{ noticia.imagen.url }}" class="card-img-top" alt="{{ noticia.titulo }}">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h1>Editar Noticia</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </form>
      </div>
    </div>
  </div>
{% endblock contenido %}

proyecto2023-main/blog/templates/noticias/inicio.html
{% extends 'base.html' %}
{% load static %}

<!-- Insertar Estilos -->
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/noticias_inicio.css' %}">
{% endblock stylesheet %}

<!-- Insertar Titulo -->
{% block titulo%} Noticias {% endblock titulo %}

{% block contenido%}
<h2 class="text-center">Todas las noticias</h2>
<hr>

<div class="row">
    <div class="col-md-12">
        <div class="d-inline-block">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Ordenar por
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="?orden=nuevas">Más nuevas</a></li>
                    <li><a class="dropdown-item" href="?orden=viejas">Más antiguas</a></li>
                    <li><a class="dropdown-item" href="?orden=alf">De la A a la Z</a></li>
                </ul>
            </div>

            <div class="btn-group" role="group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Categorías
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {% for c in categorias %}
                        <li><a class="dropdown-item" href="?id={{c.pk}}">{{c.nombre}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="mt-3">
            <a href="{% url 'noticias:registrar_noticia' %}" class="btn btn-primary">Agregar noticia</a>
        </div>
    </div>
</div>

<div class="row mt-4 noticias-container">
    {% for noticia in noticias %}
    <div class="col-md-4 mb-4">
        <div class="card">
            <img src="{{ noticia.imagen.url }}" class="card-img-top" alt="Noticia Imagen">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'noticias:detalle' noticia.pk %}">{{ noticia.titulo }}</a></h5>
                <p class="card-text">{{ noticia.cuerpo }}</p>
                <p>{{ noticia.fecha }}</p>
                <p>Categoría: {{ noticia.categoria_noticia }}</p>
                <a href="{% url 'noticias:detalle' noticia.pk %}" class="btn btn-primary">Ver más</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock contenido%}

proyecto2023-main/blog/templates/noticias/inicio_hugo.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%} noticias {% endblock titulo %}

{% block contenido%}
<br>
<br>
<h2>Soy las noticias</h2>
<div class="crear_noticia">
    <button type="submit"><a href="{% url 'noticias:registrar_noticia' %}">CREAR NOTICIA</a></button>
</div>
<a href="{% url 'noticias:inicio' %}"> Todas</a>
{% for c in categorias %}
<a href="?id={{c.pk}}">{{c.nombre}}</a>
{% endfor %}

{% for noticia in noticias %}
<Div style="background-color: rgb(214, 195, 110); margin: 1vw 1vw 1vw 20vw; width: 60vw; border-style: solid;border-color: rgb(236, 132, 28);;">
    <h2>titulo:<a href="{% url 'noticias:detalle' noticia.pk %}"> <strong>{{ noticia.titulo }}</strong></a></h2>
    <p><em>{{ noticia.cuerpo }}</em></p>
    
    <img src="{{ noticia.imagen.url }}" alt="" width="340">

    <p>{{noticia.fecha}} / <strong>{{noticia.categoria_noticia}}</strong></p>

</Div>
{% endfor %}

{% endblock contenido%}

proyecto2023-main/blog/templates/noticias/login.html
{% extends 'base.html' %}
{% load static %}

{% block contenido%}
<head>
    <title>Inicio de sesion</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mt-5 shadow">
                <div class="card-body">
                    <h3 class="card-title text-center">Iniciar Sesion</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block mt-3">Iniciar Sesión</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock contenido%}

proyecto2023-main/blog/templates/noticias/noticias_pro.html
<!DOCTYPE html>
<html>
<head>
  <title>proyecto2023</title>
  <link rel="repositorio\blog\static\css\styles.css" href="styles.css">
</head>
<body>
    <div>
        <button type = "submit"><a href="{% url 'home' %}" style="color: rgb(90, 44, 196); text-decoration: none ; font-weight: bold;" >   Categorias  </a></button> <!-- muestra un boton -->
        <button type = "submit"> <a href="{% url 'nosotros' %}" style="color: white; text-decoration: none ; font-weight: bold;" > RPG</a> </button> <!-- muestra un boton -->
        <button type = "submit"><a href="{% url 'noticias:inicio' %}" style="color: white; text-decoration: none ; font-weight: bold;" >  AVENTURAS </a></button> <!-- muestra un boton -->
        <button type = "submit"><a href="{% url 'noticias:contacto' %}" style="color: white; text-decoration: none ; font-weight: bold;" > TERROR </a></button> <!-- muestra un boton -->
        <button type = "submit"> <a href="{% url 'juegos' %}" style="color: white; text-decoration: none ; font-weight: bold;" > Juegos </a> </button> <!-- muestra un boton -->
      </div>
  <header>

    <ul id="categories">
      <li class="category"></li>
      <li class="category">RPG</li>
      <li class="category">AVENTURAS</li>
      <li class="category">CARRERAS</li>
      <!-- Puedes agregar más categorías aquí -->
    </ul>
  </header>
  <main>
    <!-- Contenido del blog -->
  </main>
  <script src="repositorio\blog\static\js\script.js"></script>
</body>
</html>

proyecto2023-main/blog/templates/noticias/registrar_noticia.html
{% extends 'base.html' %}
{% load static %}
<!-- Insertar Estilos -->
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/registrar_noticias.css' %}">
{% endblock stylesheet %}
<!-- Insertar Titulo -->
{% block titulo%} Registrar Nuevas Noticias {%endblock titulo%}

{% block contenido%}
    <div class="form-container">
        <h1>FORMULARIO DE NOTICIAS</h1>
        <h2>No te olvides de completar todos los formularios y no olvidarte ningun detalle</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Registrar noticia</button>
        {% if form.errors %}
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        </form>
    </div>
{% endblock contenido%}

proyecto2023-main/blog/templates/noticias/registro.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}

<head>
    <title>Registro de Usuario</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/registro.css' %}">
</head>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5 shadow">
                <div class="card-body">
                    <h3 class="card-title text-center">Registro de Usuario</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block mt-3">Registrarse</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

  {% endblock contenido%}