proyecto2023-main/blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

# Urls de app noticias
urlpatterns = [

    path('', views.inicio, name="inicio"),

    # url para el detalle de la noticia por pk
    path('detalle/<int:pk>/', views.Detalle_Noticias, name='detalle'),

    # url del formulario de contacto
    path('contacto', views.Contact.as_view(), name="contacto"),

    # URL COMENTARIO
    path('comentario', views.Comentar_Noticia, name='comentar'),
    
    # crear noti
    path('registrar_noticia/', views.CrearNoticia.as_view(), name='registrar_noticia'),

    # Registro de Usuarios
    path('registro/', views.Registro.as_view(), name="registro"),
    
    path('editar/<int:pk>/', views.editar_noticia, name='editar_noticia'),

    path('borrar/<int:pk>/', views.borrar_noticia, name='borrar_noticia'),
]

proyecto2023-main/blog/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [

    path('registro/', views.Registro.as_view(), name="registro"),

]

proyecto2023-main/blog/blog/urls.py
from django.contrib import admin
# importamos include para poder trabajar con las urls de noticias
from django.urls import path, include
# from apps.noticias import views
from . import views

# url del login
from django.contrib.auth import views as auth
from django.conf.urls.static import static

from django.conf import settings

# URL PRINCIPAL
urlpatterns = [
    # path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    # path para la url de la vista de home
    path('', views.home, name="home"),
    # path tiene 3 parametros direccion url, funcion de la vista(views),
    # path de nosotros
    path('nosotros/', views.nosotros, name="nosotros"),

    # ---------- URL APP NOTICIA-----------
    path('noticia/', include('apps.noticias.urls')),

    # LOGIN
    # path('usuarios/login', views.login, name='login')
    path('login/', auth.LoginView.as_view(template_name='noticias/login.html'), name='login'),
    # ultimo error de la clase solucionado
    # path('logout/', auth.LoginView.as_view(), name='logout'),
    # cambiar LoginView por LogoutView
    path('logout/', auth.LogoutView.as_view(), name='logout'),

    # Registro
    # path('usuarios/', include('apps.usuarios.urls')),
    
     #Mejores Juegos
    path("recomendaciones/", views.recomendaciones, name="recomendaciones")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semana13/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

proyecto2023-main/blog/apps/noticias/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usuario(AbstractUser):
    pass 

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nombre


class Noticia(models.Model):
    titulo = models.CharField(max_length=150)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.titulo


class Contacto(models.Model):
    nombre = models.CharField(max_length=60)
    correo = models.EmailField()
    asunto = models.CharField(max_length=40)
    texto = models.TextField()

    def __str__(self) -> str:
        return self.nombre
#


class Comentario(models.Model):
    texto = models.TextField(null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    

    def __str__(self) -> str:
        return f"{self.noticia} {self.texto}"

proyecto2023-main/blog/apps/usuarios/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):
    pass

proyecto2023-main/blog/apps/noticias/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Contacto, Noticia, Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='apellido', required=True)
    password1 = forms.CharField(
        label='contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='contraseña2', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

class LoginForm(AuthenticationForm):
    class Meta:
        fields = ['username', 'password']




class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = "__all__"

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ('titulo', 'cuerpo', 'imagen', 'categoria_noticia')
        

proyecto2023-main/blog/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario


class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='apellido', required=True)
    password1 = forms.CharField(
        label='contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='contraseña2', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

blog/views.py
from django.shortcuts import render

# Create your views here.

proyecto2023-main/blog/apps/noticias/views.py
# dependencias de Django
from django.shortcuts import render, HttpResponse, redirect
# Importacion de Modelos
from .models import Noticia, Categoria, Comentario, Contacto
#importacion de Formularios
from .forms import NoticiaForm, ContactoForm, RegistroForm
# importamos reverse lazy para los comentarios
from django.urls import reverse_lazy
# importacion del decorador para verificar logueo
from django.contrib.auth.decorators import login_required
# Clase mixta para verificar que un usuario este logueado antes de ejecutar
from django.contrib.auth.mixins import LoginRequiredMixin
# Importacion de la dependencia para crear vistas en la BD 
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.views import View
from .forms import LoginForm
from django.shortcuts import render, get_object_or_404, redirect

# Clases de Registro de Usuarios


class Registro(View):
    template_name = 'noticias/registro.html'

    def get(self, request):
        form = RegistroForm() 
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegistroForm(request.POST) 
        if form.is_valid():
            form.save()
            return redirect('login')
        return render(request, self.template_name, {'form': form})


class Login(View):
    template_name = 'noticias/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Lógica para el inicio de sesión exitoso (opcional)
                return redirect('inicio')
        return render(request, self.template_name, {'form': form})




@login_required
def inicio(request):
    contexto = {}
    id_categoria = request.GET.get('id', None)
    orden = request.GET.get('orden', 'nuevas')  # Obtenemos el parámetro 'orden' de la URL o establecemos el valor predeterminado 'nuevas'

    if id_categoria:
        noticias = Noticia.objects.filter(categoria_noticia=id_categoria)
    else:
        noticias = Noticia.objects.all()  # una lista

    if orden == 'nuevas':
        noticias = noticias.order_by('-fecha')  # Ordenamos por fecha más reciente (descendente)
    elif orden == 'viejas':
        noticias = noticias.order_by('fecha')  # Ordenamos por fecha más antigua (ascendente)
    elif orden == 'alf':
        noticias = noticias.order_by('titulo')  # Ordenamos alfabéticamente por título (ascendente)

    contexto['noticias'] = noticias

    cat = Categoria.objects.all().order_by('nombre')
    contexto['categorias'] = cat

    return render(request, 'noticias/inicio.html', contexto)


@login_required
def Detalle_Noticias(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk=pk)
    contexto['noticia'] = n

    c = Comentario.objects.filter(noticia=n)
    contexto['comentarios'] = c

    return render(request, 'noticias/detalle.html', contexto)

@login_required
def editar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = NoticiaForm(instance=noticia)

    return render(request, 'noticias/editar.html', {'form': form, 'noticia': noticia})

@login_required
def borrar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    
    if request.method == 'POST':
        noticia.delete()
        return redirect('noticias:inicio')  

    return render(request, 'noticias/borrar.html', {'noticia': noticia})



class CrearNoticia(LoginRequiredMixin, CreateView):
	model = Noticia
	form_class = NoticiaForm
	template_name = 'noticias/registrar_noticia.html'
	success_url = reverse_lazy('noticias:inicio')
	
	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.autor = self.request.user
		return super(CrearNoticia, self).form_valid(form)




class Contact(CreateView):
    model = Contacto
    form_class = ContactoForm
    template_name = 'contacto/formulario.html'
    success_url = reverse_lazy('noticias:registrar_noticia')
    
    def form_valid(self, form):
        contacto = form.save(commit=False)
        return super(Contact, self).form_valid(form)


@login_required
def Comentar_Noticia(request):
    comentario = request.POST.get('comentario', None)
    user = request.user
    noti = request.POST.get('id_noticia', None)
    noticia = Noticia.objects.get(pk=noti)
    coment = Comentario.objects.create(
        usuario=user, noticia=noticia, texto=comentario)
    return redirect(reverse_lazy('noticias:detalle', kwargs={"pk": noti}))

proyecto2023-main/blog/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.
# importts
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegistroForm


class Registro(CreateView):
    # forms django
    form_class = RegistroForm
    success_url = reverse_lazy('login')
    template_name = 'usuarios/registro.html'

proyecto2023-main/blog/blog/views.py
from django.shortcuts import render, redirect
from apps.noticias.models import Noticia

def home(request):
    # Obtener las últimas 4 noticias ordenadas por fecha de publicación descendente
    noticias = Noticia.objects.order_by('-fecha')[:4]

    # Pasar las noticias al contexto
    context = {'noticia_0': noticias[0],
               'noticia_1': noticias[1],
               'noticia_2': noticias[2],
               'noticia_3': noticias[3]}
    
    return render(request, 'home.html', context)


def nosotros(request):
    return render(request, 'nosotros.html', {
        "saludo": "Hola mundo",
        "nombre": "Soy el contexto",
        "autor": "Dani"
    })
    
def recomendaciones(request):
    return render(request, "juegos.html")

proyecto2023-main/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="https://kit.fontawesome.com/883aaa2c72.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Ubuntu&display=swap" rel="stylesheet">
        
        {% block stylesheet %}

        {% endblock stylesheet %}
        <title>blog| {% block titulo%} {% endblock titulo%}</title>
    </head>
<body class="contenedor">
    <!-- Navegador Responsive -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <!-- Logo -->
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'img/PROYECTO_GAMER.png' %}" alt="Logo" width="300px">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Botones -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <!-- boton home -->
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <!-- boton nosotros -->
                <a class="nav-link" href="{% url 'nosotros' %}">Nosotros</a>
              </li>
              <li class="nav-item">
                <!-- boton Noticias -->
                <a class="nav-link" href="{% url 'noticias:inicio' %}">Noticias</a>
              </li>
              <li class="nav-item">
                <!-- boton Noticias -->
                <a class="nav-link" href="{% url 'noticias:contacto' %}">Contacto</a>
              </li>
              <li class="nav-item">
                <!-- boton Noticias -->
                <a class="nav-link" href="{% url 'recomendaciones' %}">Recomendaciones</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <div class="conectado">
                <h3> {{ user.username }} </h4>
            </div>
            <div class="logout_container">
                <a href="{% url 'logout' %}" class="cerrar">Cerrar sesion</a>
            </div>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <!-- boton Noticias -->
                <a class="nav-link login" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <!-- boton Noticias -->
                <a class="nav-link signin" href="{% url 'noticias:registro' %}">Registrate</a>
              </li>
            {% endif %}
          </div>
        </div>
      </nav>
    <div class="contenido">
      {% block contenido %}
      
      {% endblock contenido%}
    </div>
    <footer class="pie-pagina">
      <div class="grupo1">
          <div class="box">
            <figure>
              <a href="#" class="logo-footer-container">
                <img src="{% static 'img/logito.png' %}" alt="Logo del Footer" class="logo-footer-img" width="300px">
              </a>
            </figure>
          </div>
          <div class="box">
              <h2>SOBRE NOSOTROS</h2>
              <P>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe, nisi?</P>
              <P>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe, nisi?</P>
          </div>
          <div class="box">
              <h2>SIGUENOS</h2>
              <div class="red-social">
                  <a href="#" class="fa fa-facebook"></a>
                  <a href="#" class="fa fa-instagram"></a>
                  <a href="#" class="fa fa-youtube"></a>
                  <a href="#" class="fa fa-twitter"></a>
              </div>
          </div>
      </div>
      <div class="grupo2">
          <small>&copy; 2023 <b>PROYECTO GAMER</b> - Todos Los Derechos Reservados</small>
      </div>
  <footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

proyecto2023-main/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
<!-- Insertar Estilos -->
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock stylesheet %}
<!-- Insertar Titulo -->
{% block titulo%} home {%endblock titulo%}

{% block contenido%}
<div class="content-container">
  <div class="main-container">
    <div id="carouselExampleCaptions" class="carousel slide">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
       </div>
      <div class="carousel-inner">
        <div class="carousel-item active carousel-container">
          <img src="{{ noticia_0.imagen.url }}" class="d-block w-100 img-fluid noticia-img" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <div class="noticias-container">                
              <h5 class="noticia-titulo">{{ noticia_0.titulo }}</h5>
              <p class="noticia-cuerpo">{{ noticia_0.cuerpo }}</p>
            </div>  
          </div>
        </div>
        <div class="carousel-item carousel-container">
          <img src="{{ noticia_1.imagen.url }}" class="d-block w-100 img-fluid noticia-img" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <div class="noticias-container">
              <h5 class="noticia-titulo">{{ noticia_1.titulo }}</h5>
              <p class="noticia-cuerpo">{{ noticia_1.cuerpo }}</p>
            </div>  
          </div>
        </div>
        <div class="carousel-item carousel-container">
          <img src="{{ noticia_2.imagen.url }}" class="d-block w-100 img-fluid noticia-img" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <div class="noticias-container">
              <h5 class="noticia-titulo">{{ noticia_2.titulo }}</h5>
              <p class="noticia-cuerpo">{{ noticia_2.cuerpo }}</p>
            </div>  
          </div>
        </div>
        <div class="carousel-item carousel-container">
          <img src="{{ noticia_3.imagen.url }}" class="d-block w-100 img-fluid noticia-img" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <div class="noticias-container">
              <h5 class="noticia-titulo">{{ noticia_3.titulo }}</h5>
              <p class="noticia-cuerpo">{{ noticia_3.cuerpo }}</p>
            </div>  
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>
<div class="bienvenida">
  <h1 class="titulo-pagina">BIENVENIDO A PROYECTO GAMER</h1>
  <h3 class="descripcion-pagina">Aqui encontraras muchas noticias sobre juegos indie! Te invitamos a que puedas registrarte y formar parte de esta comunidad</h3>
</div>
{% endblock contenido%}

proyecto2023-main/blog/templates/home_hugo.html
{% extends 'base.html' %}
{% load static %}
<!-- Insertar Estilos -->
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock stylesheet %}
<!-- Insertar Titulo -->
{% block titulo%} home {%endblock titulo%}

{% block contenido%}


<h1 style="text-align: center;"> ULTIMAS  NOTICIAS </h1>

<div class="content-container"; style="text-align: center; ">
    <!--
    <div class="main-container">
        <h1>TITULO H1</h1>
        <h2>H2 SEGUNDO TITULO -  -- - - - - - - -SEGUNDO TITULO -  -- - - - - - - -SEGUNDO TITULO -  -- - - - - - - -SEGUNDO TITULO -  -- - - - - - - -</h2>
        <h3>H3 TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- TERCERA LINEA DE TITULOS  - - -- </h3>
    </div>
    <aside class="aside-container">
        <h2>titulo costado¡=?</h2>
        <h3>descripcion constado descripcion constado descripcion constado descripcion constado descripcion constado </h3>
    </aside>
    -->


        <div style="color: rgba(15, 177, 0, 0.5); background-color: rgba(15, 177, 0, 0.5); width: 40vw; border-style: solid; margin-right: 5px; height: 630px;">
            <div>
                <h3><a href="{% url 'noticias:detalle' 1 %}">noticia 1</a></h3> 
                <img src="../static/img/1.jpg" alt="imagen noticia 1" width="200px">
                <p style="color: bisque;"> comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario  </p>
            </div>
        </div>
        <div style="color: rgba(201, 49, 12, 0.5); background-color: rgba(201, 49, 12, 0.5); width: 40vw; border-style: solid; margin-right: 5px; height: 630px;">
            <div>
                <h3><a href="{% url 'noticias:detalle' 2 %}">noticia 2</a></h3> 
                <img src="../static/img/2.jpg" alt="imagen noticia 1" width="200px">
                <p style="color: bisque;"> comentario comentario comentario comentariocomentario comentario comentario comentariocomentario comentario comentario comentariocomentario comentario comentario comentariocomentario comentario comentario comentariocomentario comentario comentario comentariocomentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario  </p>
            </div>
        </div>
        <div style="color: rgba(243, 239, 8, 0.5); background-color: rgba(243, 239, 8, 0.5); width: 40vw; border-style: solid; margin-right: 5px; height: 630px;">
            <h3><a href="{% url 'noticias:detalle' 1 %}">noticia 3</a></h3> 
                <img src="../static/img/3.jpg" alt="imagen noticia 1" width="200px">
                <p style="color: bisque;"> comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario  </p>
        </div>
   
        <div style="color: rgba(48, 27, 236, 0.5); background-color: rgba(48, 27, 236, 0.5); width: 40vw; border-style: solid; margin-right: 5px; height: 630px;">
        <div>
            <h3><a href="{% url 'noticias:detalle' 1 %}">noticia 4</a></h3> 
            <img src="../static/img/4.jpg" alt="imagen noticia 1" width="200px">
            <p style="color: bisque;"> comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario comentario  </p>
        </div>
    </div>



    <aside class="aside-container" style="color: rgb(116, 116, 116); background-color: white;">
            <!-- 
            <h2>titulo costado¡=?</h2>
            <h3>descripcion constado descripcion constado descripcion constado descripcion constado descripcion constado </h3>
            -->
            <button type="submit"><a href="">ver todas</a></button>



    </aside>





</div>
    <body style="background-image: url(/static/img/fondo_home.jpg);background-repeat: no-repeat;background-size: 1370px 900px;"> 
    
    
    </body>
{% endblock contenido%}

proyecto2023-main/blog/templates/juegos.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %} 
<link rel="stylesheet" href="../static/css/juegos.css">
{% endblock stylesheet %}
{% block titulo%} 8 Juegos Indie {%endblock titulo%}

{% block contenido%}
<h1 style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size:xx-large; color: blue;" > LOS RECOMENDADOS </h1>

<!-- partial:index.partial.html -->
<!-- TARJETA 1 -->
<main class="page-content">
<!-- TARJETA 2 -->
  <div class="card">
    <div class="content">
      <h2 class="title">Stardew Valley</h2>
      <p class="copy">Stardew Valley es un juego apasionante para hacer de granjero a solas o en compañía.</p>
      <button class="btn"><a href="https://es.stardewvalleywiki.com/Stardew_Valley_Wiki" target="_blank" rel="nooper noreferrer"> pagina Oficial </a></button>
    </div>
  </div>
<!-- TARJETA 3 -->
  <div class="card">
    <div class="content">
      <h2 class="title">Undertale</h2>
      <p class="copy">Undertale es un RPG enfocado en las decisiones. Puedes matar, intentar dialogar o hasta reclutar enemigos como buenos aliados. </p>
      <button class="btn"><a href="http://www.undertale-spanish.com/" target="_blank" rel="nooper noreferrer"> pagina Oficial </a></button>
    </div>
  </div>
<!-- TARJETA 4 -->
<!-- TARJETA 5 -->  
  <div class="card">
    <div class="content">
      <h2 class="title">Divinity: Original Sin 2</h2>
      <p class="copy">Dentro de los RPGs, Divinity: Original Sin 2 es uno de los mejores que puedes jugar.</p>
      <button class="btn"><a href="https://es.bandainamcoent.eu/divinity-original-sin-2/divinity-original-sin-2-definitive-edition" target="_blank" rel="nooper noreferrer"> pagina Oficial </a></button>
    </div>
  </div>
<!-- TARJETA 6 -->
  <div class="card">
    <div class="content">
      <h2 class="title">This War of Mine</h2>
      <p class="copy">La guerra ha azotado a los civiles y debes ayudarles a sobrevivir a toda costa.</p>
      <button class="btn"><a href="https://www.wargaming.cl/product/this-war-of-mine-espanol" target="_blank" rel="nooper noreferrer"> pagina Oficial </a></button>
    </div>
  </div>
<div style="margin-top: 30px;"> </div>

<!-- TARJETA 7 -->
<!-- TARJETA 8 -->
  
</main>
<!-- partial -->
{% endblock contenido%}